# #ddev-generated
# This file is placed by the justafish/ddev-drupal-xb-dev addon.
webimage_extra_packages: ["libgtk2.0-0", "libgtk-3-0", "libgbm-dev", "libnotify-dev", "libnss3", "libxss1", "libasound2", "libxtst6", "xauth", "xvfb"]
