#!/bin/bash

#ddev-generated
## Description: Run commands in the experience builder ui directory
## Usage: xb-ui
## Example: ddev xb-ui npm run build

if [ -d "web/core" ]; then
  cd web/modules/contrib/experience_builder/ui && "$@"
else
  cd modules/contrib/experience_builder/ui && "$@"
fi
